### ISSUE TITLE
Exposed Github Key

### ISSUE THREAD

**Issue by chrisbog94** [suzuki-shunsuke/go-ci-env#8]
Potential security breach. See /cienv/github-actions/env_test.go

**Comment by suzuki-shunsuke** [comment]
@chrisbog94 Thank you for your report.
I checked https://github.com/suzuki-shunsuke/go-ci-env/blob/3a11485c6bd5e24f071ced88bb00815d9b2ab6f2/cienv/github-actions/env_test.go ,
but I can't understand which the code has a problem.

Does `Github Key` mean the GitHub Personal Access token?

**Comment by suzuki-shunsuke** [comment]
If you don't want to write the detail here (public repository), please send an email to me.
You can know my email from git log.

**Comment by suzuki-shunsuke** [comment]
@chrisbog94

**Comment by suzuki-shunsuke** [comment]
I close this issue because there is no response.
